### ISSUE TITLE
It is not possible to uninstall scons.

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#1567]
This issue was originally created at: 2007-02-23 17:45:25.
This issue was reported by: `issues@scons`.
issues@scons said at 2007-02-23 17:45:25
>When installing scons with either the win32 installer executable or "python
>setup.py install" there is no way to uninstall the application.
> 
>I originally installed scons from the .zip and when attempting to upgrade to the
>latest version I used the executable. Both installs worked but now I have files
>for both somewhere on my system and when I do scons --version I get the old
>version and not the new one.

issues@scons said at 2007-02-23 17:47:50
>Found the uninstaller for the .exe version in add/remove programs (this should
>be documented, even if it does seem "obvious") but I still can't figure out how
>to remove the old version.

stevenknight said at 2008-06-26 17:55:08
>Set priority and target milestone per bug party.

gregnoel said at 2008-12-26 13:20:26
>Adjust triage of issues.

stevenknight said at 2009-11-10 18:00:19
>stevenknight => issues@scons

**Comment by Anutrix** [comment]
Any fixes yet? This seems to be major issue.
I want to quickly uninstall version 3.0.5 to install 3.1.2 .

**Comment by mwichmann** [comment]
Note the windows installer is no longer supported, so that's become a non-issue.

If you install with `setup.py` you need to remove the files manually. If you don't know the files, the best suggestion I have is redo the install with an option to capture the files, and use that to drive a manual uninstall:
```
python setup.py install --record installlog.txt
```
`installog.txt` will now contain a list of what was installed.

**Comment by Anutrix** [comment]
It's not exactly non-issue because 3.1 branch is fairly new and people shifting from 3.0.5 to 3.1 will have trouble unless they see your method.
It would be helpful if we were to put this "Reinstall with recording to uninstall" info on the FAQ of the main website or somewhere easy to look.

**Comment by mwichmann** [comment]
The non-issue part had to do with the Windows installer.  I see 3.0.0 was actually released with a `.exe` installer, but none of the drops since then starting with 3.0.1 have been.

We'll wait to see what the maintainer wants to do about uninstall hints.  We've updated the install section of the User Guide quite a bit recently, it definitely indicates a preference for a `pip` install now.

**Comment by bdbaddog** [comment]
@Anutrix as @mwichmann said the windows installer's no longer supported.  So fixing it so it will uninstall is not likely to happen.

I'm assuming that uninstalling via windows settings didn't work?

If not, the following should be a brute force way to remove the files installed by SCons windows installer from your python3.7 install.

```
rmdir /s C:\Program Files\Python37\scons
rmdir /s C:\Program Files\Python37\Lib\site-packages\scons-*
rmdir /s C:\Program Files\Python37\Lib\site-packages\scons
del C:\Program Files\Python37\Scripts\scons*.*
```

If you had installed via pip (which is the current recommendation), this would be a non-issue.
Also we generally recommend using a virtualenv.  Since in the worst case you can just delete the whole virtualenv and not alter your stock python install.

I'm going to close this bug as going forward pip installs can be uninstalled.
We'll have the info above to point people in the right direction.

**Comment by Anutrix** [comment]
Thx. I understand. Also, note I can't test the old thing since it's all gone and now I am working fine with Scons 3.1.2 installed via pip with Python 3.8 .

> I'm assuming that uninstalling via windows settings didn't work?

I don't know what you mean by this. If you mean from `Programs and Features`, it didn't have scons there.

> The non-issue part had to do with the Windows installer. I see 3.0.0 was actually released with a `.exe` installer, but none of the drops since then starting with 3.0.1 have been.

Since, I had 3.0.5, it probably means I had it installed it via pip not Windows Installer.
But the issue was that it was not listed in `pip install`'s output.

I hadn't cleaned up in a while so it was good chance to do so. I was planning to finally start using virtual environments soon. Guess it's high time.

Anyways no trouble anymore.
