### ISSUE TITLE
Replace base classes of 'collections.UserList' with 'list'

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2338]
This issue was originally created at: 2009-02-10 22:14:16.
This issue was reported by: `gregnoel`.
gregnoel said at 2009-02-10 22:14:16
>It's now possible to create classes based on built-in types.  The classes based
>on 'collections.UserList' should be converted to use 'list' as a base type.

gregnoel said at 2009-02-10 22:14:57
>Set dependency.

stevenknight said at 2009-02-22 08:10:02
>Reprioritizing and reassigning per bug party triage.
> 
>(Actually, we didn't specifically settle on assigning this to you, Greg.  I
>assigned it to you because it feels of the same piece as the Fixer work you've
>been spearheading.  Kick it back if you feel that's inappropriate.)

stevenknight said at 2009-02-22 08:13:49
>Actually, I see now that we suggested Nate takes this (and 2238) but I'm not
>sure if he has a tigris.org username.  Please reassign as appropriate.

garyo said at 2012-09-01 10:01:49
>Bumping all old issues targeted for past releases to 2.x.

garyo said at 2012-09-01 10:04:01
>de-assigning all tickets assigned to Greg Noel (no longer working on SCons)

gregnoel said this issue depends on #2337 at 2009-02-10 22:14:57.

**Comment by mwichmann** [comment]
Turns out this is hard to do, due to subtleties with how Python handles lists (it cheats, for purposes of optiimization), and also hard due to some of the ways we use some of the lists based on UserList. Despite the wide number of comments that you should just sublass list, UserList (and the suitable abstract base class in collections.abc) are designed for subclassing.

Here's a discussion by one experienced Pythonista: https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/

Suggest we drop this one.

**Comment by bdbaddog** [comment]
Yes. I don't see a reasonable way to do this unless python's list's implementation makes more internal visible. Closing.
