### ISSUE TITLE
When running scons on a FIPS compliant machine scons still try to use md5 even if the C and python libraries are missing.

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2949]
This issue was originally created at: 2014-05-24 07:57:52.
This issue was reported by: `bsucha`.
bsucha said at 2014-05-24 07:57:52
>When running scons on a FIPS compliant machine scons still try to use md5 even if the C and python libraries are missing. This causes scons to fail the at the first file it tries to compile.
> 
>This can be easily solved by updating Util.py to try to initialize the md5 library before defining the functionality and catching the ValueError thrown when it doesn't exist.
> 
```python
try:
   import hashlib
   hashlib.md5()  # add this line, this will try to cause the initialization of the md5 functionality.
except ImportError:
   pass
except ValueError: # add this line
   pass           # add this line
```
> 
>This will allow scons to continue properly and fall back to its missing md5 mode.
> 
> 
>Specific machine: RHEL6 2.6.32-358.2.1.el6.x86_64 #<span></span>1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Comment by rruhge** [comment]
Is there any effort to work on this bug? We would like to use SCons on our fips enabled machine but the following error does not let it work as is.

>>> import hashlib
>>> hashlib.md5() 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips

Thanks for any feedback!

**Comment by bdbaddog** [comment]
@rruhge - Feel free to submit a pull request and we'll try to get it merged in quickly.

See: https://github.com/SCons/scons/wiki/GitWorkflows for info on how to do this.

**Comment by mwichmann** [comment]
I have, actually, a branch which "fixes" this.  But I haven't done anything with it other than occasionally rebase to stay up to date, as there didn't seem to be much enthusiasm last time someone brought it up, and there are unasnwered questions. As in... what to do if md5 is unavailable?  Not use file signatures at all?  That's not really great.  Switch to a different mechanism?  (my experiment did sha1, which also isn't "secure", but the signatures are not used for any security purpose in scons).  Is it necessary to add a configuration mechanism, where the user selects the digest form they want?  is it necessary to teach scons to detect the format from an existing signature database? I can certainly make a "patch" available if someone wants to look at it as a starting point.

**Comment by bdbaddog** [comment]
What hashes are FIPS compliant?

**Comment by rruhge** [comment]
From a document I just found: (SHA-1, SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224
and SHA-512/256) are the SHS hashes that are compliant.  I tested with sha-1 and it worked.

**Comment by rruhge** [comment]
Sure sha1 isn't secure, but if we're not looking for a security purpose here, that would work for us, it does not break scons.

**Comment by mwichmann** [comment]
A "FIPS-compliant Python" is a thing, and it only excludes md5. 
https://docs.python.org/3/library/hashlib.html

**Comment by mwichmann** [comment]
... which by the way you can test on by editing the `__always_supported` list in `hashlib.py` in your Python installation.

**Comment by bdbaddog** [comment]
Ugh.. we'd probably need to push a sconsign revision to support changing the hash properly.
What kind of mess will we get into if the sconsign has the other hash (not the one being used), and/or both types of hash?

Lots of extra rebuilds?

**Comment by mwichmann** [comment]
that's why I considered my branch a proof-of-concept, not something ready to push.

**Comment by rruhge** [comment]
Could scons keep md5 but switch to sha1 (or something else) with a command line option?

**Comment by bdbaddog** [comment]
@rruhge - The issue is what I put in previous response. How to handle same sconsign file, but one run has md5, one has sha. Also how to allow explicitly selecting.

**Comment by mwichmann** [comment]
I should add, there's a second place that uses md5 that would be affected, beyond file signatures: the md5 module is used to generate uuids for visual studio integration.  the better answer there is to switch to the uuid module to generate a uuid... I worked on that as well, not sure if it was all correct.

**Comment by bdbaddog** [comment]
@rruhge - Are you using/generating visual studio project files?

**Comment by rruhge** [comment]
@bdbaddog - We are not.

**Comment by bdbaddog** [comment]
@mwichmann - Can you push a PR with your code and then point @rruhge at it to try?  It may take a number of iterations to get something we can merge.

**Comment by mwichmann** [comment]
#3447

**Comment by rruhge** [comment]
I gave it a try, this still didn't work.  This seems to be because hasattr(hashlib, 'md5') still returns true, even though calling hashlib.md5() returns a ValueError.  Could exception handling be used instead to cycle through the hash options?

**Comment by mwichmann** [comment]
yeah, sure.  indeed hasattr is "unpreferred" these days.

maybe:
```
try:
    from hashlib import md5
    hashfunc = hashlib.md5
    assert md5  # quiet pyside about unused md5
except ImportError:
...etc...
```

**Comment by rruhge** [comment]
I did this to make it work:

`try:
    if hasattr(hashlib, 'md5'):
        md5 = True
        hashfunc = hashlib.md5
        assert hashlib.md5()
except ValueError:
    md5 = False

if ~md5:
    try:
        if hasattr(hashlib, 'sha1'):
            # failover to sha1 if md5 is missing
            md5 = 'sha1'
            hashfunc = hashlib.sha1
            assert hashlib.sha1()
    except ValueError:
        md5 = False`

**Comment by rruhge** [comment]
The attempt to import it works as well, so an ImportError was not thrown.

I was able to make it work with this code: 

```
try:
    if hasattr(hashlib, 'md5'):
        md5 = True
        hashfunc = hashlib.md5
        assert hashlib.md5()
except ValueError:
    md5 = False

if ~md5:
    try:
        if hasattr(hashlib, 'sha1'):
            # failover to sha1 if md5 is missing
            md5 = 'sha1'
            hashfunc = hashlib.sha1
            assert hashlib.sha1()
    except ValueError:
        md5 = False
```

**Comment by mwichmann** [comment]
okay, so the way md5 is excluded on your Python must be different than how I did mine.  Obviously, yours is the interesting testcase :)

**Comment by rruhge** [comment]
@mwichmann - Do you want me to go ahead and put in a pull request then, or are you going to merge it into your branch, or do you still want to discuss the sconsign issues?

**Comment by mwichmann** [comment]
doesn't make any difference to me (I certainly don't need the credit).  we have to wait to see what will make the maintainer happy as far as completing the work :)

**Comment by bdbaddog** [comment]
so the fips version of python has an md5.py but it's bogus? so catching importerror won't do the trick? where can we get a FIPS version of python?

**Comment by rruhge** [comment]
Sorry I didn't think of this before.  We are not using the version of python that ships with the OS because it is a very old version.  We are using a version of Python 3 that you can get from the OS vendor, but it's an extra.  Since this is the case, it may not actually be a FIPS compliant version of Python, so it still has md5, and somewhere at the OS security level may be where the md5 call is being blocked.  I'm not 100% sure on this but it's my guess as to why the import still works, but the actual call throws the error.  We are still on the OS indicated in the original bug report.  That said, I can't think of a way to recreate the issue other than setting up a virtual machine in FIPS mode.

**Comment by bdbaddog** [comment]
Any way you can help us to reproduce the python you have would be very useful.

**Comment by rruhge** [comment]
Understood, I will keep thinking on it but I don't have any ideas right now other than if a developer would be able to work on a FIPS enabled RedHat 6 VM.  I'm mostly convinced we're being blocked at the OS level, not the Python level.

**Comment by rruhge** [comment]
@mwichmann - could you go ahead and merge my snippet above into your branch? I'm ok with this, since you already have the pull request out there and have done it before.  And sorry guys, I've looked around and don't have any other way that I've found to reproduce the issue.

**Comment by rruhge** [comment]
Is this still something we can pursue? I have no other way of providing a FIPS version, other than someone setting up a VM configured that way.

**Comment by bdbaddog** [comment]
@rruhge  - how would I set up a VM as such?

**Comment by mwichmann** [comment]
it would be good to know, since the try I made didn't catch the case @rruhge was running into.  The Python core team certainly knows about this case but doesn't yet seem to have a consensus on what Python should do... for example this ticket is still open after 9 years: https://bugs.python.org/issue9216.  I believe in a true FIPS-compliant system openssl will be built in a mode that rejects non-FIPS hashes, and this may be the failure mode being seen?

**Comment by rruhge** [comment]
I think to do this, you'd have to use a Redhat 6 VM (can get it free with a developer license, not sure if CentOS has FIPS mode).  During setup, there should be an option to enable FIPS.  Our system is using the Redhat software collection 'rh-python36' (https://access.redhat.com/documentation/en-us/red_hat_software_collections/3/html/3.3_release_notes/chap-installation#sect-Installation-Install), which installs python 3.6.3.  I'm betting if you can just install python3 yourself from the python website you'd get the same behavior, and it may be easier.  This is done because Redhat 6 itself does not provide python 3.

If you use the software collection method, python will be placed at /opt/rh/rh-python36/root/usr/bin/python.  Our System Admins did this install so I'm not sure of the exact steps other than what's in that documentation, but I can give it a try this weekend at home too if I have time to give more specific instructions, if that helps.

Edit: After looking a bit, looks like CentOS also supports FIPS mode, so CentOS 6 could probably also be used if preferred.

**Comment by bdbaddog** [comment]
Downloading a specific OS to get to this would honestly be the last choice.
It looks like python can be built with FIPS compliant openssl.
https://hussainaliakbar.github.io/build-python-3-6-0-from-source-with-fips-validated-openssl-on-ubuntu-16-04-lts/

**Comment by mwichmann** [comment]
This is irritating, it looks like from some non-Python material on the web that the FIPS mode now in openssl prohibits default access to _any_ low-level hashing algorithm, and you're instead required, by default, to use a higher-level interface.  That means in the more modern instances of this (RHEL/CentOS 7 and 8) sha1, sha256, etc would *all* be unavailable as opposed to just md5sum as seen in the 6.x series.  I can't prove this without a working instance, I'll see if I can flip the FIPS switch in a copy of my CentOS vm. There is a bypass because "it's complicated" and this is not always disallowed (and the way SCons uses secure hashes ought to qualify for the exception), but I don't know if Python would use the bypass.  Python's Blake implementation is used directly without talking to openssl so it might be the workaround if this turned out to be true. This is what Python's `hashlib` does:
```
    if name in {'blake2b', 'blake2s'}:
        # Prefer our blake2 implementation.
        return __get_builtin_constructor(name)
    try:
        f = getattr(_hashlib, 'openssl_' + name)
```

**Comment by mwichmann** [comment]
nevermind, I read that wrong, `_hashlib/__init__.py` does use the "higher level" openssl EVP interface, so the other algorithms should not be turned off after all.

**Comment by mwichmann** [comment]
I know this has been ages, but it's now possible (not yet in a released version) to run scons in a mode that doesn't use md5.  See the above-mentioned PR #3709.

**Comment by bdbaddog** [comment]
@mwichmann - did we figure out a way to identify that SCons is running in a FIPS environment? ( And then change the default hash only in that case?)

Maybe using this code: https://github.com/SCons/scons/issues/2949#issuecomment-531913910

**Comment by mwichmann** [comment]
As I think I said, I built up a FIPS-compliant CentOS 6 according to the instructions I was able to find, and it didn't cause the import of md5 to fail. So we could try, but I don't have a way to test.

**Comment by jcassagnol-public** [comment]
I was recently running a build on a FIPS-compliant system, and ran into a FIPS throw:
```sh
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS:
  File "/home/jcassagnol/4.0/libraries/jalop/JALoP-2.0.0.2-beta/SConstruct", line 165:
    if not conf.CheckCC():
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/SConf.py", line 712:
    ret = self.test(context, *args, **kw)
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/SConf.py", line 1024:
    res = SCons.Conftest.CheckCC(context)
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/Conftest.py", line 154:
    ret = _check_empty_program(context, 'CC', text, 'C')
  File "/home/cassagnol/.local/lib/python3.6/site-packages/SCons/Conftest.py", line 231:
    return context.CompileProg(text, suffix)
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/SConf.py", line 912:
    return not self.TryBuild(self.env.Object, text, ext)
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/SConf.py", line 880:
    return self.sconf.TryBuild(*args, **kw)
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/SConf.py", line 606:
    textSig = SCons.Util.hash_signature(sourcetext)
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/Util.py", line 1784:
    m = _get_hash_object(hash_format)
  File "/home/jcassagnol/.local/lib/python3.6/site-packages/SCons/Util.py", line 1761:
    return _HASH_FUNCTION()
```
Is this intentional though? I'm wondering if the legacy SConstruct is doing something silly or unintentional.
The hacky way I got it working was to change `SCons/Util.py:1743` 
```python
set_hash_format(None)
```
to
```python
 set_hash_format("sha256")
```
But a "real" fix would probably involve changing _get_hash_object to default to sha256 on None passed to it, so something like this:
```python
def _get_hash_object(hash_format):
    """Allocates a hash object using the requested hash format.

    Args:
        hash_format: Hash format to use.

    Returns:
        hashlib object.
    """
    if hash_format is None:
        if _HASH_FUNCTION is None:
            from SCons.Errors import UserError  # pylint: disable=import-outside-toplevel

            raise UserError('There is no default hash function. Did you call '
                            'a hashing function before SCons was initialized?')
        # default to md5, if available, otherwise default to sha256. This is a patch around FIPS compliance issues in the hashing library.
        # currently the python support libraries identify md5 as supported even in FIPS mode, and then throw a ValueError on first access here.
        try:
            return _HASH_FUNCTION()
        except ValueError:
            set_hash_format("sha256") 
            return _HASH_FUNCTION()
...
```
My comment and patch are in the public domain, let me know if you want a pull request.

**Comment by mwichmann** [comment]
When the change to allow a choice of hash formats was made, it wasn't done specifically for the FIPS situation, but we hoped it would cover it - unfortunately, nobody could get a test result. As mentioned in earlier comments, I had tried to assemble a FIPS Centos VM setup per the instructions I could find, but I could never get it to throw errors, so it must not have been set up right.

The result you see is clearly not one we'd want, blowing up with an unhelpful message isn't okay.

**Comment by jcassagnol-public** [comment]
All good! :D
The SConstruct file is from a very old product, so calling CheckCC might not be an intended use-case. It appears to be a self-check intended for unit tests rather than something folks are supposed to call.
We had already hit the FIPS compliance issue before in SCons which we worked around by disabling FIPS mode, generally folks running FIPS-compliant systems are used to seeing that type of message, and it's a fairly descriptive error for FIPS-related problems (FIPS was blamed in the original error).
Recently the ability to turn off FIPS mode was taken from us, so I've been patching our internal build scripts to get them working once they deploy it across our small domain.
As far as I know that's the only issue I've run into so far with the --hash-algorithm=sha256 branch,.
I'll poke at it some more and see if it's building correctly, but so far the PR was a good one as far as I can tell.
The system I'm using is a RHEL 8.4 system.
I was using the pip3 whl-file install for 4.2.0 rather than the direct github source. I will try testing it on a clean VM or container to see if the results are different. Our build scripts are designed to be run from a clean VM/container so it shouldn't be too hard to trigger it.

**Comment by bdbaddog** [comment]
If there's FIPs in your environment, it'd probably be worthwhile to add

`SetOption('hash_format','sha256')`

In your SConstructs.

That said, if you're willing to work with us, we'd like to have SCons "do the right thing" when it's run in a FIPS environment.
Please let us know if you can spare some time to sort this out properly.
(also probably easier to do so via our Discord Server https://discord.gg/pejaFYrD9n if that's a possibility)

**Comment by bdbaddog** [comment]
Page on how to setup FIPS environment:
https://ubuntu.com/blog/building-and-running-fips-containers-on-ubuntu

(thanks @jcassagnol-public )
