### ISSUE TITLE
debug=explain gets confused by Value objects

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#2995]
This issue was originally created at: 2015-03-02 00:57:15.
This issue was reported by: `thosrtanner`.
thosrtanner said at 2015-03-02 00:57:15
Example SConstruct
 
```py
e = Command('wibble', 'a', 'echo boo >> $TARGET')
Depends(e, Value('a value'))
```
 
Run this, note it builds
 
now change the SConstruct to this
 
```py
e = Command('wibble', 'a', 'echo eek >> $TARGET')
Depends(e, Value('a value'))
```
 
`scons --debug=explain` says:
 
```console
scons: Building targets ...
scons: rebuilding `wibble' because:
`a value' is no longer a dependency
`a value' is a new dependency
echo boo >> wibble
```
 
But "a value" hasn't changed. The command action has.

**Comment by mwichmann** [comment]
Went hunting for whether there was any existing bug on a changed dep not being reported as changed, but rather "x is no longer a dependency" followed by "x is a new dependency".  Since I found this one, I'll drop some incomplete analysis here. This might apply to a couple of other issues as well (#2996 and #2932 could be other candidates).

Basically, the `Node` class's `explain` method does no work relating to the main flow of the program, it is only called to format a message once SCons already knows a target needs rebuilding (this is actually good news on one front: if there are fixes that can be made local to the method, they're sure not to break anything else since it just creates text messages for printing if `debug=explain` is selected).  It gets some things wrong in doing this work.  It builds a list of old and new bkids and signatures, and zips each set into a dictionary. The bkids are class instances (I found them to be `Node.FS.File`).  If one of these is changed then it doesn't match its unchanged counterpart - there is no special `__eq__` method that defines how these nodes are compared, so it's just identity - or in the case of dict lookup, hashing.  So we get for example the case of reporting that something is no longer a dependency:
```
removed = [x for x in old_bkids if not x in new_bkids]
if removed:   # format "no longer" message here
```
The the old and new nodes will differ from the Python view of equality, so we'll find an instance of this - something in old is not "in" new, and vice versa as the next check will find, even though we are referring to the same file, thus we get the pair of messages, and don't get the expected message that the file has changed.  
I'm not yet clear how we exactly get here - I was chasing this on the change of a source file.  The analysis of built files seems to come out correct - e.g. if an object file is changed, libraries which use it are correctly identified as being rebuilt because the object changed, and then binaries which use the library get a similar correct message.  Whether this is "value objects" or something different I'm not sure.
You can change the handling a little bit so it compares, say, names (or rather the result of the local `stringify` function), but that doesn't solve the full problem, as you still need to look up the signatures for the node, and since the dictionary uses node instances as they key, you'll get an error. That is, this bit of code:
```
try:
    changed = _decider_map[k.changed_since_last_build](k, self, osig[k])
except DeciderNeedsNode as e:
    changed = e.decider(self, osig[k], node=self)
```
which comes into play once you've decided the node may be changed: we get an id from new and try to look up its former signatures in old, and that will throw a `KeyError` since the nodes don't match - again the equality question.
It's possible that adding comparison dunder methods (`__eq__` and `__ne__`) would make this work, but a quick off-the-cuff experiment showed this to break something else, so I didn't chase further.

**Comment by mwichmann** [comment]
Okay, I guess the information comes from here:
```py
    def prepare_dependencies(self):
        """
        Prepares a FileBuildInfo object for explaining what changed

        The bsources, bdepends and bimplicit lists have all been
        stored on disk as paths relative to the top-level SConstruct
        directory.  Convert the strings to actual Nodes (for use by the
        --debug=explain code and --implicit-cache).
        """
```

**Comment by mwichmann** [comment]
This is just annoyingly complex. The obvious way ought to be to define comparison of `File` instances as equal if their pathname is equal.  However adding an `__eq__` method to `File` (or to its base class `Base`) turns out not to be workable, even though there is a similar `__le__` method defined in `Base`  already. Getting the string representation of the class involves quite a bit of work (see the `_get_str` and `_save_str` methods of `Base`) and ends up doing a comparison, which calls the `__eq__` again which calls the `__str__` again. Voila, recursion exception.

In `explain()`, it is easy to "fix" the first step, namely looking for removed nodes, just by adding an extra check on the paths. The second step decides if the nodes are new, or if modified. If you add the additional check for path here, then the potential new node, which then is found not to be new, is passed on to logic which does the wrong thing with it, because it doesn't "exist" in the list of stored nodes - the same object equality problem.

**Comment by bdbaddog** [comment]
Duplicate of #2023
