### ISSUE TITLE
No documentation on --install-sandbox which is used by Install() builder

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3007]
This issue was originally created at: 2015-06-22 18:09:57.
This issue was reported by: `bdbaddog`.
bdbaddog said at 2015-06-22 18:09:57
>There's currently no documentation nor does it display in scons -H.
> 
>--install-sandbox

bdbaddog said at 2015-06-22 18:10:30
>Fix -H issue first, then change subcomponent to documentation?

**Comment by mwichmann** [comment]
`--install-sandbox` is not added in the "normal" place in the code, but by the install tool, perhaps this is why the help doesn't make it into the display?

**Comment by mwichmann** [comment]
github auto-closed this because it was mentioned in the doc PR, but the Help part of the report is not addressed.  After digging further:

- `Tool/install.py` adds the option using `AddOption`, which is unlike any other option in scons, which are all set up in `Script/SConsOptions.py`
- the help message from the option is not pushed into the full help string
- the `AddOption` only runs if the tool is set up which only happens if it is used - sconscripts contain `Install` (or relatives) calls, **and** they are actually going to be used.  If you run `scons -H`, it never gets to the tool's `generate` function, so the option is never added, so it can't possibly appear in the help.

Repairing that would take some rethinking.  Moving the option definition to `SConsOptions.py` would appear to be the simplest.
