### ISSUE TITLE
Empty file and missing file have same csig.

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3014]
This issue was originally created at: 2015-11-19 12:21:07.
This issue was reported by: `wblevins001`.
wblevins001 said at 2015-11-19 12:21:07
>While working on other patches I discovered that the csig for a FS Node is the same for empty files and missing files.
> 
>From a correctness standpoint, the hash for these files should not be the same.
> 
>Take for example a lock file (just an empty file used as a lock for other processes like side-effects). If an empty file and a missing file have the same csig, then there are possible issues.
> 
>This shouldn't be hard to fix, but it might cause rebuilds.

wblevins001 said at 2016-01-14 17:13:03
>I looked into this; the md5 function doesn't handle passing in None as a parameter; thus, this probably isn't worth pursuing.

wblevins001 said at 2016-01-14 17:13:54
>Unless we want to write None to the cache? I'm not sure if that's a good idea, but it would be accurate...

Votes for this issue: 1.

**Comment by mwichmann** [comment]
Doesn't seem like a missing file should be assigned a signature... what is the signature *of*?

**Comment by mwichmann** [comment]
So I see this code: 
```python
def get_content_hash(self):
    if not self.rexists():
        return MD5signature('')
    ...
```

The `hexdigest` methods of the various hashlib hash objects all return a hash if given nothing at all, and that's the same as the hash of an empty string, that is:
```
>>> m = hashlib.md5()
>>> m.hexdigest()
'd41d8cd98f00b204e9800998ecf8427e'
>>> m.update(b'')
>>> m.hexdigest()
'd41d8cd98f00b204e9800998ecf8427e'
```

So given the scons code, there's definitely no way to distinguish between no file and empty file, they both end up hashing `''`.  Is this what's wanted? The above snip could return something different in the case of no entry - rather than trying to mess with `None` values, it could hash some chosen string or a random number like perhaps `uuid.uuid4()`.

**Comment by bdbaddog** [comment]
Interesting.. that code has been around since 2008..

**Comment by bdbaddog** [comment]
Yes.  A constant for empty files makes sense.
Though how can we ensure there's no hash collision?
What happens if there's no specified value? or (None)?

**Comment by mwichmann** [comment]
Collisions unlikely, even with a "deprecated" hash like md5.  Empty file will still hash to the same thing it has, same as empty string.  Missing files could either  all hash to the same thing via `return MD5signature('_MISSING_FILE_')` or to something that was unique over each call like `return MD5signature(uuid.uuid4().bytes)`.  I'm not clear that inidividual missing-file entries need to be unique; the complaint here originally is just not being unable to separate "no file" from "empty file".
```
>>> m = hashlib.md5()
>>> n = hashlib.md5()
>>> m.update(b'')
>>> n.update(b'_MISSING_FILE_')
>>> m.hexdigest()
'd41d8cd98f00b204e9800998ecf8427e'
>>> n.hexdigest()
'515d5382550d6006a195b6dc26f63712'
```
Not even sure there's a *real* problem, possibly just a theoretical one, even if that's a classic sentinel problem...

**Comment by bdbaddog** [comment]
Indeed empty file != missing file

**Comment by mwichmann** [comment]
I never followed up on this. Do a PR with the one-liner change to hash some unlikely-to-match string for missing file?

**Comment by bdbaddog** [comment]
Hmm. does md5 spec have a special hash for none or empty or such? An unreachable but valid value?

**Comment by mwichmann** [comment]
No, it just hashes the string you give it.  I had suggested a string that's really unlikely to be a file's contents above, anything like that should work (I don't care what the string is).

**Comment by bdbaddog** [comment]
o.k make the string __SCONS_MAGIC_EMPTY_FILE_STRING__

**Comment by mwichmann** [comment]
Thinking about this a little more, there are some oddities here. `File.get_csig` is the only caller of `File.get_content_hash`, where the change was considered. It does so this way:
```python
            try:
                if self.get_size() < File.md5_chunksize:
                    contents = self.get_contents()
                else:
                    csig = self.get_content_hash()
```
In the case of the non-existent file, we're not going to get to the `get_content_hash` call, because `get_size` will have returned zero - it has the same special-case check for `self.rexists()` and returns 0 if not; thus the size will be less than chunk size and we go off in a different path.  This idea of nonexistent == empty/zero-length seems to be somewhat ingrained.

**Comment by mwichmann** [comment]
One further look: `get_content_hash` is indeed never called on a nonexistant file during a full test suite run, those having first been intercepted by `get_size`. What's more, `get_size` is memoized, so after setting the size to zero there, it is saved for subsequent calls:
```python
        if self.rexists():
            size = self.rfile().getsize()
        else:
            size = 0
        self._memo['get_size'] = size
```
It's still possible to use a sentinel value for no-file, but it would mean it would have to be checked every time, don't know if that's an acceptable cost.
