### ISSUE TITLE
Methods added to environments with Scons.Util.AddMethod do not env.Clone correctly

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3028]
This issue was originally created at: 2016-05-03 07:51:15.
This issue was reported by: `pw201`.
pw201 said at 2016-05-03 07:51:15
>Methods added to an environment instance with the SCons.Util.AddMethod 
>function do not clone correctly with env.Clone(): they're bound to the old 
>object, not the cloned one. If you use the AddMethod method on the instance 
>itself, this works, because the method adds them to the instance's 
>added_method's list. 
> 
>Although the example in the docs uses the AddMethod function on a class and 
>the AddMethod method on an instance of the class, as the function is 
>documented to work on an "object", it's not clear that this shouldn't work 
>on an instance of Environment rather than only working on the Environment 
>class.
> 
>That is, I assert that given
> 
>def funct(self):
>   return self
> 
>then
> 
>env = Environment()
>AddMethod(env, funct)
>env1 = env.Clone()
>print env1, env1.funct()
> 
>and 
> 
>env = Environment()
>env.AddMethod(funct)
>env1 = env.Clone()
>print env1, env1.funct()
> 
>should both print the same object twice (or the first example should 
>generate an exception when AddMethod is used on an instance rather than a 
>class). Currently only the second example does so.

bdbaddog said at 2016-05-03 10:35:07
>Thanks for the bug report.
>Please bring your issue to the scons users mailing list before filing a bug.
>This is the standard scons policy.  The idea is to avoid filing duplicate bugs,
>get more eyes on the issue which may provide a faster fix and/or work around. 
>Also this helps identify issues which are user error and not issues with SCons.
> 
>http://scons.org/bugs.html
> 
>While it looks like your issue is a new one, please still bring this to the
>users mailing list.

pw201 said at 2016-05-04 09:30:05
>Sorry, but the page at http://scons.tigris.org/bug-submission.html doesn't 
>mention the mailing list. I won't be subscribing to lots of mails just to 
>report a bug. I have provided a clear statement of the problem and a 
>reproduction case. Feel free to fix it or not.

bdbaddog said at 2016-05-04 16:57:15
>Fair enough. Though the volume of email on the users mailing list is not that
>high.  (as you can see here:
>http://news.gmane.org/gmane.comp.programming.tools.scons.user)
> 
>I'll update the page to indicate the preferred process for reporting a bug.
>I'll pass along a link to our users mailing list as well to get more eyes on it.
> 
>Thanks for reporting the issue.

**Comment by mwichmann** [comment]
This  is interesting... and the behavior of `env.AddMethod()` seems to be pretty intentional. When called, it's not the method itself that is added, but a `MethodWrapper` instance, which stores the method. Then when there's a Clone, the act of cloning creates a new wrapper which will hold the same method. 

Expanding the bits of the original example, the `env.AddMethod` case:
```
env = Environment()
env.AddMethod(funct)
print("Added to:", env, "=", env.funct)
print("which wraps:", env.funct.method)
env1 = env.Clone()
print("Cloned to", env1, "=", env1.funct)
print("which wraps:", env.funct.method)
```
Which gives us:
```
Funct at <function funct at 0x7f16f5361268>
...
Added to: <SCons.Script.SConscript.SConsEnvironment object at 0x7f16f5236dd8> = <SCons.Environment.MethodWrapper object at 0x7f16f523c048>
which wraps: <function funct at 0x7f16f5361268>
Cloned to <SCons.Script.SConscript.SConsEnvironment object at 0x7f16f523c2b0> = <SCons.Environment.MethodWrapper object at 0x7f16f51db048>
which wraps: <function funct at 0x7f16f5361268>
```
So the question is, is the different behavior of `Clone()` intentional?  Here we don't get `MethodWrapper` objects, we get methods bound into the environment they are added to, as if they were methods of that environment in other words.
```
print("Funct at", funct)
env = Environment()
AddMethod(env, funct)
print("Added to:", env, env.funct)
env1 = env.Clone()
print("Cloned to:", env1, env1.funct)
```
Giving:
```
Funct at <function funct at 0x7f16f5361268>
Added to: <SCons.Script.SConscript.SConsEnvironment object at 0x7f16f538a1d0> <bound method funct of <SCons.Script.SConscript.SConsEnvironment object at 0x7f16f538a1d0>>
Cloned to: <SCons.Script.SConscript.SConsEnvironment object at 0x7f16f538a470> <bound method funct of <SCons.Script.SConscript.SConsEnvironment object at 0x7f16f538a1d0>>
```
In any case, `Clone` and `env.Clone` are different code paths, one is in `SCons.Util` and the other in `SCons.Environment`
Inconsistent, but is this actually a problem, in the end?

**Comment by mwichmann** [comment]
Swung back and took another look.  `AddMethod` (`SCons.Util`) and `env.AddMethod` (`SCons.Environment`) are different functions.  The latter appends any added methods to an attribute named, helpfully, `added_methods` in the instance it's acting on.  This attribute is then used when cloning to rebind added methods.  If you use `AddMethod` this never happens, so there's no rebinding. Perhaps fix this in documentation ("do not try to AddMethod to an Environment instance, use env.AddMethod"  kind of thing)? It looked like a fairly trivial fix in `SCons.Util.AddMethod` but it turns out you don't bind the right thing in that case, and trying to get it from `SCons.Environment` leads to a circular import warning that I don't feel like unraveling.

**Comment by bdbaddog** [comment]
How about a warning when if you do that? ( `if isinstanct(BaseEnvironment, object0)` ?)

**Comment by mwichmann** [comment]
A warning might make sense... what would the wording be?   When I tried a quick hack I looked for whether the object had a `added_methods` attribute, since that's set in the object initializer, which detected the case nicely enough, I just couldn't "fix things up" easily at that point.

**Comment by bdbaddog** [comment]
Hmm.. Is it always bad to use AddMethod(env,...) ? Or only if you expect it to propagate when you Clone()?
If you move the import into the function involved (and thus narrow it's scope) I think that can work around circular import issues..

**Comment by mwichmann** [comment]
If you cloned, the wrong thing gets passed as "self" (you end up with the proxy for the cloned parent).  That may or may not be an actual problem (I presume at least something or this issue wouldn't have been filed).

**Comment by mwichmann** [comment]
Don't think we can "fix" the imports, Util just can't import the other bits of scons, which basically all use something from Util. Could maybe move the definition of MethodWrapper to Util...

**Comment by bdbaddog** [comment]
Ah..yes that'd sometimes be BAD.. but often o.k. which is kinda worse than always bad or good.. ;)

**Comment by mwichmann** [comment]
It does become a simple fix with MethodWrapper moved over. (I have a testcase for the unit test) Whether it's a good idea or not to even try...
