### ISSUE TITLE
Support for Python3?

### ISSUE THREAD

**Issue by nowox** [SCons/scons#3103]
I am surprised that I found no issues about Python3. I noticed SCons only supports Python2.7 (from the readme)

>Running SCons requires Python version 2.7 or later **(Python 3 is not yet supported)**. There should be no other dependencies or requirements to run SCons.

I friendly reminder that Python 2.7 will retire in 2 years and 1 month (https://pythonclock.org/). 

Is there a short term plan to extend the SCons support to Python3?

**Comment by kblomqvist** [comment]
SCons 3.x already works with Py3.

**Comment by bdbaddog** [comment]
Firstly, we ask that users bring their issues to the scons users mailing list before creating an issue.
The keeps duplications, etc to the minimum.

Secondly, SCons has supported Python 2 and Python 3.5+ since the 3.0.0 release.

Closing This issue. Please bring further discussions or issues the the users mailing list.
You can join the mailing list here:
https://pairlist4.pair.net/mailman/listinfo/scons-users

**Comment by bdbaddog** [comment]
BTW. Where did you find that text? If it's still the tree, we'll update it.

**Comment by nowox** [comment]
@bdbaddog Ok I didn't know that. It is said on the README

> Python 3 is not yet supported

Which means that SCons does not support Python 3. I think this README file should be fixed then...

**Comment by bdbaddog** [comment]
Ahh.. Weird. grepping my sandbox didn't find that. O.k I'll fix it.

**Comment by bdbaddog** [comment]
O.k. Updated.
