### ISSUE TITLE
VS2019 Support

### ISSUE THREAD

**Issue by bdbaddog** [SCons/scons#3346]
Add support for VS2019

Current Known issues:
SCons will use VS2019 but will misidentify the version as 14.1.
Until VS2019 support is listed in CHANGES.txt it's not a supported version.

Please add any other issue found with VS 2019 here.

Work is in progress.

**Comment by LeonarddeR** [comment]
I've looked at the code, and I think there are several issues:

In the first place, the Visual Studio numbering seems  to be wrong. Note that Visual Studio (VS) and Visual C++ (VC) numbering is out of sync starting with VS2017.

year | VS | VC
-----|---|--
2015 | 14.0 | 14.0
2017 | 15.0-15.9 | 14.1
2019 | 16.0-? | 14.2

Therefore, I'd suggest to update the visual studio code (vs.py) to use the actual version numbers. This means that for 2017, a change is required from 14.1 to 15.0. 2019 should be refered to as 16.0

In the second place, vswhere is used incorrectly. It looks like the `-version` command line parameter requires a version range instead of a single version. For VS 2017, this ought to be [15.0,16.0]. For VS2019, this should be [16.0,17.0]. Therefore, I'd like to suggest the following changes to from tool.MSCommon.vc

* Remove VC 14.1 from _VCVER_TO_PRODUCT_DIR
* Ad a new dictionary `_VCVER_TO_VSWHERE_VERSION_RANGE`, like this:

    ```
_VCVER_TO_VSWHERE_VERSION_RANGE = {
	"14.1": "[15.0,16.0]",
	"14.2": "[16.0,17.0]",
}
```

    In find_vc_pdir, directly fallback to find_vc_pdir_vswhere if msvc_version is not in _VCVER_TO_PRODUCT_DIR but in _VCVER_TO_VSWHERE_VERSION_RANGE.
* Change the vswhere command to properly set the `-version` command line parameter according to what's in _VCVER_TO_VSWHERE_VERSION_RANGE

If you would like any assistance with this, let me know.

**Comment by jcbrill** [comment]
I do not think it matters, but the vswhwere version range should be an open-ended interval rather than a closed-end interval as above (i.e., a close parenthesis rather than close square bracket):
```
_VCVER_TO_VSWHERE_VERSION_RANGE = {
    "14.1": "[15.0,16.0)",
    "14.2": "[16.0,17.0)",
}
```

The following minimal changes below were hacked into a python 2.7 installation on 32-bit windows and appear to be working as expected.  Quick tests appear to work.  The changes have not been tested on 64-bit windows yet.  

As I made the following changes before reading the post above. the dictionary mapping the msvc version to vswhere version is not the same as above.

Added the following definition for msvs 2019 to vs.py:
```
    # Visual Studio 2019
    VisualStudio('14.2',
                 vc_version='14.2',
                 sdk_version='10.0A',
                 hkeys=[],
                 common_tools_var='VS160COMNTOOLS',
                 executable_path=r'Common7\IDE\devenv.com',
                 batch_file_path=r'VC\Auxiliary\Build\vsvars32.bat',
                 supported_arch=['x86', 'amd64', "arm"],
                 ),
```

Added/extended the following declarations for msvc 2019 to vc.py:
```
_VCVER = ["14.2", "14.1", "14.0", "14.0Exp", "12.0", "12.0Exp", "11.0", "11.0Exp", "10.0", "10.0Exp", "9.0", "9.0Exp","8.0", "8.0Exp","7.1", "7.0", "6.0"]

_VCVER_TO_VSWHERE_VER = {
    '14.2' : '[16.0, 17.0)',
    '14.1' : '[15.0, 16.0)',
}

_VCVER_TO_PRODUCT_DIR = {
    '14.2' : [
        (SCons.Util.HKEY_LOCAL_MACHINE, r'')],
    '14.1' : [
        (SCons.Util.HKEY_LOCAL_MACHINE, r'')], # Visual Studio 2017 doesn't set this registry key anymore
```

Added a lookup from the msvc version to vswhere version and then use the vswhere version variable in the query in find_vc_pdir_vswhere in vc.py:
```
    try:
        vswhere_version = _VCVER_TO_VSWHERE_VER[msvc_version]
    except KeyError:
        debug("Unknown version of MSVC: %s" % msvc_version)
        raise UnsupportedVersion("Unknown version %s" % msvc_version)

    # For bug 3333 - support default location of vswhere for both 64 and 32 bit windows
    # installs. 
    for pf in ['Program Files (x86)', 'Program Files']:
        vswhere_path = os.path.join(
            'C:\\',
            pf,
            'Microsoft Visual Studio',
            'Installer',
            'vswhere.exe'
        )
        if os.path.exists(vswhere_path):
            # If we found vswhere, then use it.
            break

    vswhere_cmd = [vswhere_path, '-products', '*', '-version', vswhere_version, '-property', 'installationPath']
```
Note: the MSVC_VERSION documentation in Tool/msvc.xml would need to be updated as well.

**Comment by mwichmann** [comment]
Keep going, guys!  It helps to have people who actually use Windows contribute to fixing the Windows issues :)

**Comment by jcbrill** [comment]
Mats and Bill,

The attached zip file contains a minimal patch to provide MSVS 2019 support for windows.

Comments:
- A docstring comment was modified to include raising an exception.  This was changed similar to a comment in the same file.  I'm not sure what the documentation conventions are so it should either be reviewed or removed,
- The exception raised was copied and pasted.  I did not test actually raising the exception.  However, I don't believe an invalid msvc version should get this far unless there is a source configuration error.
- The changes have not been fully tested on x64 platforms.
- The batch file included (stk_msvc.bat) is a "pure" windows batch file that configures the msvc toolsets from the windows command line.  The logic mirrors that of scons.  This has proved somewhat beneficial to check that the environment is configured correctly outside of scons.  I have used the batch file for most all major versions of MSVC since 6.0 (1998) on x86 and recent versions (2013+) on x64.

Joe

[scons-master-msvs2019-patch.zip](https://github.com/SCons/scons/files/3217360/scons-master-msvs2019-patch.zip)

**Comment by bdbaddog** [comment]
Joe,

Any chance you can submit a pull request?
We'd be glad to help you through the process if you're unfamiliar.

-Bill

**Comment by jcbrill** [comment]
Bill,

I would appreciate it if you could walk me through the process like I'm five years old.

I am not a git user.  I created a GitHub account for the sole reason of reporting an earlier scons windows x86 anomaly.  Any and all help is appreciated.

Any pointers on using MS Outlook to reply to the user mailing list correctly would also be useful.  I can't seem to get Outlook to reply to the appropriate message at the appropriate nesting of a thread in the user mailing list.

Joe

> Joe, 
> Any chance you can submit a pull request?
> We'd be glad to help you through the process if you're unfamiliar.
> -Bill

**Comment by mwichmann** [comment]
>     * A docstring comment was modified to include raising an exception.  This was changed similar to a comment in the same file.  I'm not sure what the documentation conventions are so it should either be reviewed or removed,

I think we want to keep the same docstring style within a single docstring, so instead of the more human-readable Google/NumPy style you've used, write it (lined up with the earlier markup) in the ReST style as:
`
    :raises: UnsupportedVersion blah blah`

**Comment by jcbrill** [comment]
Revised patch with ReST style docstring for raising UnsupportedVersion exception consistent with other specifications for the same function (dropped inherits from VisualCException text):
`:raises UnsupportedVersion: if the version is not known by this file`.

I removed the batch file in the previous attachment from the zip archive as well.  It is unrelated to the patch to add support for VS 2019.

[scons-master-msvs2019-patch2.zip](https://github.com/SCons/scons/files/3219532/scons-master-msvs2019-patch2.zip)

**Comment by bdbaddog** [comment]
Take a read through:
https://github.com/SCons/scons/wiki/GitWorkflows

That should (we hope) help you do your first pull request.
If something doesn't work/isn't clear. please send email to the dev mailing
list.

Can you send an initial email to users or dev mailing list? or is it only
replying to an email which is causing you issues?

**Comment by mwichmann** [comment]
I got stuck in this mess looking at something else, and the above looks good to me, with some experiments, I get the same sorts of results.

While we've got some people paying attention, what is the purpose of the "SDK version"?  right now, there's the table SupportedVSList (to which an addition for vc14.2 as appears in vs2019 is proposed above) which seems to map vs version to sdk version, but then that's used to plug in to a registry query that doesn't find anything... the only SDKs I have in the registry location it looks in are 8.0 and 8.1, but I have a lot more things in the SDK directory. 
```
HKEY_FMT = r'Software\Microsoft\Microsoft SDKs\Windows\v%s\InstallationFolder'
```
There are a ton of things called SDK by Microsoft, these seem to be the dot-net bits.  Is there something that needs fixing here?  What is this SDK search actually for in the SCons context?

**Comment by bdbaddog** [comment]
@mwichmann  - It's the platform SDK (think OS level stuff). Generally there's only certain versions which work with each version of MSVC and each OS. (Assuming I'm remembering this correctly)

Like this:https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk

They are usually optionally installable components as part of MSVS/MSVC

**Comment by jcbrill** [comment]
I can't answer what SCons is doing with the SDK version.

The SDK version _can_ be passed as a command-line argument (winsdk_version) to vcvarsall.bat.  AFAIK, SCons does not support this.

> winsdk_version 
> Optionally specifies the version of the Windows SDK to use. By default, the latest installed Windows SDK is used. To specify the Windows SDK version, you can use a full Windows 10 SDK number such as 10.0.10240.0, or specify 8.1 to use the Windows 8.1 SDK.
> 

If you are on a 64-bit version of Windows, check the following key as well:

`HKEY_FMT = r'Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v%s\InstallationFolder'`

On a windows 10, 64-bit box, the key in your post had the following SDK keys: v7.1A, v8.0A, v8.1A.  

The `Wow6432Node` key above contained the following SDK keys: v7.1A, v8.0, v8.0A, v8.1, v8.1A, v10.0.

_ProgramFiles(x86)\Microsoft SDKs\Windows_ contains sub-folders: v7.0, v7.1A, v8.0, v8.0A, v8.1, v8.1A, v10.0A.

_ProgramFiles(x86)\Windows Kits_ contains sub-folders: 8.0, 8.1, 10, NETFXSDK

Confusing enough?

**Comment by mwichmann** [comment]
Of course it is confusing enough :)   Yeah, I see the check in Wow6432Node, that's not in the initialized bits buts is added as part of a different spot. Missed that.  Yeah, I see the same list as you there (excepting the 7.x ones, presumably versions I don't have installed).

**Comment by mwichmann** [comment]
sigh... must have hit the wrong key, wasn't done yet.  The `Wow6432Node` check doesn't seem to apply to the sdks - the class has a method `get_sdk_dir` that does not do that, as can be seen in the debug log if you turn it on. It *is* applied in `find_vc_pdir`. 

With debugging turned on, the find_sdk_dir check seems to only find the aforementioned 8.x ones for my setup

**Comment by jcbrill** [comment]
In recent versions of MSVS, there is a batch file _winsdk.bat_ in the sub-folder _Common7\Tools\vsdevcmd\core\winsdk.bat_.

I am not familiar with this batch file.

When an SDK version is not specified, the batch file appears to search the registry in the following order of key prefixes:
- HKLM\SOFTWARE\Wow6432Node
- HKCU\SOFTWARE\Wow6432Node
- HKLM\SOFTWARE
- HKCU\SOFTWARE

For 2019, the actual registry queries are segmented by SDK version 10 and 8.1.

For 10:
```
for /F "tokens=1,2*" %%i in ('reg query "%1\Microsoft\Microsoft SDKs\Windows\v10.0" /v "InstallationFolder"') DO (
    if "%%i"=="InstallationFolder" (
        SET WindowsSdkDir=%%~k
    )
)
```

For 8.1:

```
if "%WindowsSdkDir%"=="" for /F "tokens=1,2*" %%i in ('reg query "%1\Microsoft\Microsoft SDKs\Windows\v8.1" /v "InstallationFolder"') DO (
    if "%%i"=="InstallationFolder" (
        SET WindowsSdkDir=%%k
    )
)
```

Note:  This may only apply to recent versions of MSVS.

My guess is that omission of "HKLM\SOFTWARE\Wow6432Node" in the SCons SDK search is an error of omission.  

It appears that the "HKLM\SOFTWARE\Wow6432Node" keys should be queried before before the ""HKLM\SOFTWARE" keys in SCons.

Note:  The MS batch file also queries the Current User keys after the Local Machine keys.

**Comment by mwichmann** [comment]
Thanks for all the info! I had actually patched in a check to try the `Wow6432Node` entry first just as you suggest; it worked but didn't work - because it then takes the path obtained from the registry and uses it to look for a file named `SetEnv.cmd`, which does not appear to be used any longer, I can only find one of those on the system and it's not in a mainline sdk. Probably that means newer installations need to be following more of the stuff you dug up.
```
DEBUG:SCons.Tool.MSCommon.common:MSCommon/sdk.py: trying to find SDK 10.0
DEBUG:SCons.Tool.MSCommon.common:find_sdk_dir(): checking registry:Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v10.0\InstallationFolder
DEBUG:SCons.Tool.MSCommon.common:find_sdk_dir(): Trying SDK Dir: C:\Program Files (x86)\Windows Kits\10\
DEBUG:SCons.Tool.MSCommon.common:find_sdk_dir(): sanity check C:\Program Files (x86)\Windows Kits\10\bin\SetEnv.Cmd not found
```
> My guess is that omission of "HKLM\SOFTWARE\Wow6432Node" in the SCons SDK search is an error of omission.

Yes, in the sense that it was written too long ago and didn't know it needed to.  This is why I was fishing for if anyone knew what the sdk information was actually used for.  Without tracing the whole thing all the way through it looks like it's only an existence check.

**Comment by jcbrill** [comment]
My guess is that SCons may have supported versions of the msvc compiler that were distributed with the windows SDKs (i.e., command-line tools without devenv gui) that were available separate from the visual studio releases.

I believe that there were SDK msvc versions for 2005 (SDK update for vista), 2008 (sdk 7.0), and 2010 (sdk 7.1),  

I don't believe that there were SDK msvc versions for 2012 (SDK 8.0) or 2013 (SDK 8.1) but I could be wrong.

On my 32-bit windows 7 box, _setenv.bat_ exists for the v7.0 and v7.1 (but curiously not v7.1A) SDK installations which would be consistent with the SDK compiler releases.

**Comment by rhuijben** [comment]
See also https://github.com/SCons/scons/pull/3391

**Comment by jcbrill** [comment]
@mwichmann and @rhuijben 

There is an omission with both my patch above [https://github.com/SCons/scons/issues/3346#issuecomment-495931740] and https://github.com/SCons/scons/pull/3391:  the test suite has not been updated for MSVS 2019 [14.2].

Unfortunately, I am not familiar with the SCons test harness nor with msvs workspaces.  I moved to SCons from msvc 6.0 and haven't used a msvc/msvs workspace since.

A quick search yields at least the following:
- test\MSVS\MSVC_UWP_APP.py [would need to be updated]
- test\MSVS\vs-14.2-exec.py [would need to be added]
- test\MSVS\vs-14.2-files.py [would need to be added]
- test\MSVS\vs-14.2-scc-files.py [would need to be added]
- test\MSVS\vs-14.2-scc-legacy-files.py [would need to be added]
- testing\framework\TestSConsMSVS.py [would need to be updated]

There certainly could be other places that need to be updated to wire in a new version of MSVS.

One of the reasons that I have not been proactive about the patch above is that I am somewhat reluctant to add 14.2 to msvc.xml as an officially supported version without [someone] updating the test suite.

**Comment by jcbrill** [comment]
Is anyone else testing MSVS 2019 getting msvc linker warning LNK4204 when re-building a debug configuration with pdb files using the latest update to 14.21.27702?

I have interleaved 32-bit and 64-bit target dll and exe builds on a 64-bit host in both release and debug configurations.  There are inter-dependencies between the libraries and executables.  Immediately running scons a second time following a clean initial build invokes the msvc link command again for some of the build targets [_this could be an user-created dependency problem_] without compiling any of the source files (i.e., the object files have not changed).  Up until the latest 2019 update, there have been no warnings when re-linking.

Example MSVC 2019 [14.21.27702] linker warnings:

> cmore_work.obj : warning LNK4204: '??????' is missing debugging information for referencing module; linking object as if no debug info

> test.obj  : warning LNK4204: '??????' is missing debugging information for referencing module; linking object as if no debug info

> cmore_dllmain.obj : warning LNK4204: '' is missing debugging information for referencing module; linking object as if no debug info

The "?" characters are unprintable characters.

I updated to 14.21 before doing any testing so I can't be sure if the behavior was the same in 14.20 on a 64-bit host.

There are no such warnings with exactly the same build and re-build sequence using MSVC 2017 (14.16.27031) or any earlier versions.

For the initial build, the only differences between the captured stdout+stderr for 2017 and 2019 is the msvc version number when the tools are executed.  For the rebuild, other than the version numbers, the only differences are that the 2019 log contains the linker warnings.  The build sequence is the same as well as all flags and switches.

It is entirely possible the problem lies on my end.  It is curious that the warnings are not elicited _any_ with earlier versions of msvc.

**Comment by jcbrill** [comment]
Is anyone else testing MSVS 2019 getting msvc linker warning LNK4204 when re-building a debug configuration with pdb files using the latest update to 14.21.27702?

I have interleaved 32-bit and 64-bit target dll and exe builds on a 64-bit host in both release and debug configurations.  There are inter-dependencies between the libraries and executables.  Immediately running scons a second time following a clean initial build invokes the msvc link command again for some of the build targets [_this could be an user-created dependency problem_] without compiling any of the source files (i.e., the object files have not changed).  Up until the latest 2019 update, there have been no warnings when re-linking.

Example MSVC 2019 [14.21.27702] linker warnings:

> cmore_work.obj : warning LNK4204: '??????' is missing debugging information for referencing module; linking object as if no debug info

> test.obj  : warning LNK4204: '??????' is missing debugging information for referencing module; linking object as if no debug info

> cmore_dllmain.obj : warning LNK4204: '' is missing debugging information for referencing module; linking object as if no debug info

The "?" characters are unprintable characters.

I updated to 14.21 before doing any testing so I can't be sure if the behavior was the same in 14.20 on a 64-bit host.

There are no such warnings with exactly the same build and re-build sequence using MSVC 2017 (14.16.27031) or any earlier versions.

For the initial build, the only differences between the captured stdout+stderr for 2017 and 2019 is the msvc version number when the tools are executed.  For the rebuild, other than the version numbers, the only differences are that the 2019 log contains the linker warnings.  The build sequence is the same as well as all flags and switches.

It is entirely possible the problem lies on my end.  It is curious that the warnings are not elicited _any_ with earlier versions of msvc.

**Comment by bdbaddog** [comment]
> Is anyone else testing MSVS 2019 getting msvc linker warning LNK4204 when re-building a debug configuration with pdb files using the latest update to 14.21.27702?
> 
> I have interleaved 32-bit and 64-bit target dll and exe builds on a 64-bit host in both release and debug configurations. There are inter-dependencies between the libraries and executables. Immediately running scons a second time following a clean initial build invokes the msvc link command again for some of the build targets [_this could be an user-created dependency problem_] without compiling any of the source files (i.e., the object files have not changed). Up until the latest 2019 update, there have been no warnings when re-linking.
> 
> Example MSVC 2019 [14.21.27702] linker warnings:
> 
> > cmore_work.obj : warning LNK4204: '??????' is missing debugging information for referencing module; linking object as if no debug info
> 
> > test.obj  : warning LNK4204: '??????' is missing debugging information for referencing module; linking object as if no debug info
> 
> > cmore_dllmain.obj : warning LNK4204: '' is missing debugging information for referencing module; linking object as if no debug info
> 
> The "?" characters are unprintable characters.
> 
> I updated to 14.21 before doing any testing so I can't be sure if the behavior was the same in 14.20 on a 64-bit host.
> 
> There are no such warnings with exactly the same build and re-build sequence using MSVC 2017 (14.16.27031) or any earlier versions.
> 
> For the initial build, the only differences between the captured stdout+stderr for 2017 and 2019 is the msvc version number when the tools are executed. For the rebuild, other than the version numbers, the only differences are that the 2019 log contains the linker warnings. The build sequence is the same as well as all flags and switches.
> 
> It is entirely possible the problem lies on my end. It is curious that the warnings are not elicited _any_ with earlier versions of msvc.

So are you building 32 bit and 64 bit binaries into the same location based on some command line flag?

**Comment by jcbrill** [comment]
> So are you building 32 bit and 64 bit binaries into the same location based on some command line flag?

Each build target (dll, exe) has it's own build sub-folder based on: target architecture (32 or 64), compiler (msvc or mingw-w64), crt runtime (60, 80, 90, 100, 110, 120, or 140/ucrt), and configuration (release or debug).

For example
- lib-cbase
  - __build
     - 32mgw60d
     - 32mgw60r
     - 32vc140d
     - 32vc140r
     - 32mgw60d
     - 32mgw60r
     - 64vc140d
     - 64vc140r

The example above is a typical testing build: 32/64 bit MSVC 2015/2017/2019 and 32/64-bit mingw-w64 [gcc 8.1].

Due to legacy software compatibility, each library is compiled with for msvc runtime compatibility with 60, 80, 90, 100, 120, and 140/ucrt for both 32-bit and 64-bit.

The 140 builds use whichever MSVC version is installed (MSVS 2019, MSVS 2017, MSVS 2015) or, if none are installed, Mingw-W64 with custom specs file and libraries to link to the required compatible crt.

Currently, I'm using mingw-w64 gcc 8.1 for runtime compatibility with 60, 80, 90, 100, and 110 and MSVC for runtime compatibility with 120 and 140/ucrt.  Although this can be changed easily in the build script.

The home-brew script is crt-centric rather than compiler-centric.

For both msvc and mingw compiled dlls, import libraries are re-generated for both msvc and mingw with a common, shorter name using post-actions and gendef.exe, lib.exe, and dlltool.exe.

**Comment by bdbaddog** [comment]
> > So are you building 32 bit and 64 bit binaries into the same location based on some command line flag?
> 
> Each build target (dll, exe) has it's own build sub-folder based on: target architecture (32 or 64), compiler (msvc or mingw-w64), crt runtime (60, 80, 90, 100, 110, 120, or 140/ucrt), and configuration (release or debug).
> 
> For example
> 
> * lib-cbase
>   
>   * __build
>     
>     * 32mgw60d
>     * 32mgw60r
>     * 32vc140d
>     * 32vc140r
>     * 32mgw60d
>     * 32mgw60r
>     * 64vc140d
>     * 64vc140r
> 
> The example above is a typical testing build: 32/64 bit MSVC 2015/2017/2019 and 32/64-bit mingw-w64 [gcc 8.1].
> 
> Due to legacy software compatibility, each library is compiled with for msvc runtime compatibility with 60, 80, 90, 100, 120, and 140/ucrt for both 32-bit and 64-bit.
> 
> The 140 builds use whichever MSVC version is installed (MSVS 2019, MSVS 2017, MSVS 2015) or, if none are installed, Mingw-W64 with custom specs file and libraries to link to the required compatible crt.
> 
> Currently, I'm using mingw-w64 gcc 8.1 for runtime compatibility with 60, 80, 90, 100, and 110 and MSVC for runtime compatibility with 120 and 140/ucrt. Although this can be changed easily in the build script.
> 
> The home-brew script is crt-centric rather than compiler-centric.
> 
> For both msvc and mingw compiled dlls, import libraries are re-generated for both msvc and mingw with a common, shorter name using post-actions and gendef.exe, lib.exe, and dlltool.exe.

This discussion should probably be moved to the users mailing list since it's not really about VS2019 support.

**Comment by mwichmann** [comment]
So some of the work is now merged vis #3408: the description (correct or not) of VS 2019 added to the list of versions, and the work to send a more correct version arg to `vswhere` through an additional mapping table. The authors of these bits have been credited.

It would be great to resync and see what is still needed to finish up support for VS2019.  The generation of correct project files appears to be one of those items.

**Comment by mwichmann** [comment]
Any updates here from people who actually use this stuff? Is it "done" in scons 3.1.1?

**Comment by jcbrill** [comment]
I have been using scons 3.1.1 [32-bit windows 7 with Python 3.7.4] and compiling with VS2019 (14.21) targeting both 32-bit and 64-bit intel architecures without issue.  

I have not used scons 3.1.1 nearly as much on 64-bit windows 10 with Python 3.7.4, but have not experienced any issues to date.

Appears done to me.  Nice work.

P.S.:  The LNK4024 warnings in VS2019 mentioned above were my own fault and due to the custom generated pdb file names were the same for the compiler and the linker.  Making the generated pdb file names different for the compiler and linker eliminated the warnings.

**Comment by bdbaddog** [comment]
Closing based on @jcbrill 's comment above.
