### ISSUE TITLE
include __main__.py in wheel

### ISSUE THREAD

**Issue by dholth** [SCons/scons#3370]
It looks like `SCons/__main__.py` is not included in the wheel. It allows `python -m SCons` if `SCons/` is on PYTHONPATH.

**Comment by mwichmann** [comment]
Odd, the following entry appears in src/CHANGES.txt for the 3.0.0 release:

`    - Add __main__.py for `python -m SCons` in case it is on PYTHONPATH.`

Wonder where it went to? Or maybe the file was never added to the wheel.  (it was commit d31cff4a15d3adf3842826c3af8317a2ba050038; a later one removed the guarding)

**Comment by mwichmann** [comment]
and... that was you, right?  :)

**Comment by dholth** [comment]
It was me.

I notice SCons goes to great lengths to prevent itself from being imported. Any plans to reconsider?

This bug must be just a simple problem with the way scons generates its setup.py manifest.

**Comment by bdbaddog** [comment]
> It was me.
> 
> I notice SCons goes to great lengths to prevent itself from being imported. Any plans to reconsider?
> 
> This bug must be just a simple problem with the way scons generates its setup.py manifest.

Currently we overwrite global builtins in some places things like open()? so that could/will break other usages of open() if you imported scons into your code.

Supporting people using SCons as is can be challenging enough, when people start importing it and trying to use pieces of the internal logic directly (which are not published APIs).... I don't think anyone wants to sign up for that at this point.  (Or at least in many cases folks with insufficient engineering skills trying it would be very challenging to support.. ;)

**Comment by bdbaddog** [comment]
BTW I don't we've ever added code to explicitly prevent importing.

**Comment by dholth** [comment]
Importing works fine, it's just not installed in a convenient path.  I have definitely noticed you can't run two SCons commands in the same Python. I will probably continue to do what I've been doing and repackage, or do what SCons does and edit PYTHONPATH.

**Comment by dholth** [comment]
... all this is an aside to the bug which is just to update the scons manifest during build

**Comment by bdbaddog** [comment]
Merge'd your pull request.

**Comment by dholth** [comment]
Here's my pytar https://bitbucket.org/dholth/scons-pytar/commits/67dea6e8feb065e74391e805eab4a6dc48163251

I don't remember what (didn't) happen to it.
