### ISSUE TITLE
ValueError: unsupported pickle protocol: 4

### ISSUE THREAD

**Issue by tangMans** [SCons/scons#3402]
hi, in my machine install python2.7.12 and python3.5. I execute scons as follows:
[1] in python2.7.12 execute scons, run successful
[2] and then, I switch python2.7.12 to python3.5, execute scons, run successful too
[3] and then, I switch python3.5 to python2.7.12, execute scons, run failed, and print message like "ValueError: unsupported pickle protocol: 4"..

I look forward to your reply， thinks!

**Comment by mwichmann** [comment]
It's written that way. scons picks the higest available pickle protocol when writing. 
```
PICKLE_PROTOCOL = pickle.HIGHEST_PROTOCOL
```
That means once you run a Python which supports a higher protocol (4 for 3.5-3.7 and 5 for 3.8), the sconsign file will be forever unreadable by lower Python versions, and you have to remove the sconsign file(s) to proceed with those lower versions.

Whether that's a good idea or not is a question, but that's the way it is.  The notes do say that switching between Python 2 and 3 is not supported.

**Comment by acmorrow** [comment]
This isn't a perfect workaround, but for MongoDB we made different sconsign files depending on whether you were working with python3 or not.

- On the v4.2 (and newer) branches, where py3 is required: https://github.com/mongodb/mongo/blob/v4.2/SConstruct#L942

- On the older branches, where py3 is forbidden: https://github.com/mongodb/mongo/blob/v4.0/SConstruct#L904

That worked pretty well because the version of python is tied to the branch, and switching between those branches is usually a large rebuild anyway, so the loss of state isn't that bad. And once you have done a build on each branch you are "up to date" on both according to each sconsign file.

I imagine a similar trick could be used in a combined py2/3 codebase by just examining the currently running python version. Again, not perfect, but better than it not running at all!

**Comment by bdbaddog** [comment]
@acmorrow - I did try this initially but (If I remember correctly), it broke many regression tests. That said, it's likely good general solution and if that was the issue worth just fixing the regressions to handle different file names..

**Comment by tangMans** [comment]
> It's written that way. scons picks the higest available pickle protocol when writing.
> 
> ```
> PICKLE_PROTOCOL = pickle.HIGHEST_PROTOCOL
> ```
> 
> That means once you run a Python which supports a higher protocol (4 for 3.5-3.7 and 5 for 3.8), the sconsign file will be forever unreadable by lower Python versions, and you have to remove the sconsign file(s) to proceed with those lower versions.
> 
> Whether that's a good idea or not is a question, but that's the way it is. The notes do say that switching between Python 2 and 3 is not supported.

**Comment by tangMans** [comment]
Thanks for everything, delete the .sconsign.dblite run ok.

**Comment by supagu** [comment]
I'm having a similar problem, where might I find the .sconsign.dblite file?

**Comment by gganssauge** [comment]
I have recently added Python3.8 support to my C++ extension which I'm building with SCons.
That unfortunately means that the build (using tox for managing tests) doesn't work anymore, because Python3.8 uses pickle version 5 whereas Python3.6 and Python3.7 use version 4.

What's the point in using the highest protocol? In many other areas SCons is very careful to stay compatible to older Python versions - even Python2.7 still seems to be supported.

**Comment by mwichmann** [comment]
python 2.7 is gone from master now, but it's a good point.

**Comment by bdbaddog** [comment]
@gganssauge - 3.8 introduced pickle v5 (intended for serializing for in process usage mainly).  Prior to that V4 was available on all 3.5+ as the highest.   We'll address it in the next release.  But as always Pull requests are welcome. If you see an issue.  There's only so many hands working on SCons developement and far more users and people filing issues. And none of the developers are paid to work on SCons maintenance.  Also feel free to sponsor any of the developers if you'd like to help out in other ways.

**Comment by bdbaddog** [comment]
@gganssauge - as an aside the release notes do indicate that switching python versions between runs will cause rebuilds see: https://github.com/SCons/scons/blob/master/src/CHANGES.txt#L562

**Comment by edobez** [comment]
It seems now that SCons is always using the highest protocol. This was somehow a recent change, before it was fixed to protocol version 2.
Wouldn't it better to fix it to a certain version and keep it? Now there are problems when switching even between Python 3.7 and 3.8.

**Comment by mwichmann** [comment]
It's flipped around a few times.  Before being changed to HIGHEST_PROTOCOL (which introduces the Python 3.8 vs. earlier 3.x problem), it was `-2` which is actually the same thing - from the stdlib `pickle.py`:
```
        if protocol < 0:
            protocol = HIGHEST_PROTOCOL
```
Then before that is was `2`, but that was from before the Python 3 transition in SCons seriously advanced.
Python 3.8 flipped the default from 3 to 4, and the highest from 4 to 5. We could hard-code it to 4 for now, since that's been available since before the current lowest supported Python version.

**Comment by edobez** [comment]
Probably the `-2` from the previous change was just a mistake.
Anyway, yes, I agree that fixing to `4` could be beneficial. This should be just about changing one line in `compat/__init__.py`, right?

**Comment by bdbaddog** [comment]
> Probably the `-2` from the previous change was just a mistake.
> Anyway, yes, I agree that fixing to `4` could be beneficial. This should be just about changing one line in `compat/__init__.py`, right?

Yes.

**Comment by bdbaddog** [comment]
@edobez - you're actually commenting on a related but not the same issue you're having.
This issue is about py27 and pickle protocol 4.
Not PY38/37 and protocol 5

**Please move any further discussion to #3628**
