### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by 0-wiz-0** [SCons/scons#3800]
https://github.com/SCons/scons/wiki/WhySconsIsNotSlow
contains a link to bitbucket (http://www.bitbucket.org/dirkbaechle/scons_testresults) which doesn't work any longer because bitbucket stopped supporting mercurial :(

**Comment by bdbaddog** [comment]
@dirkbaechle - do you still have that repo somewhere we could post to scons's account on github?

**Comment by dirkbaechle** [comment]
Yes, I still have the repo on my local harddrive...and I think I already converted it to git. I'll check throughout the next days, but the data is definitely not lost.

**Comment by bdbaddog** [comment]
> Yes, I still have the repo on my local harddrive...and I think I already converted it to git. I'll check throughout the next days, but the data is definitely not lost.

Can you push the content up into this repo? (You should have full access)
https://github.com/SCons/performance

**Comment by dirkbaechle** [comment]
Old contents of scons_testresults and scons_testsuite have been pushed to their new home at the "scons-performance" repo. Please check, and close this issue if everything looks correct.
Note, that the Wiki page https://github.com/SCons/scons/wiki/WhySconsIsNotSlow (mentioned above, in the issue description) isn't reachable at the moment. There seems to be some more work required, in order to restore the old linkage and content of the WhySConsIsNotSlow topic...

**Comment by bdbaddog** [comment]
> Old contents of scons_testresults and scons_testsuite have been pushed to their new home at the "scons-performance" repo. Please check, and close this issue if everything looks correct.
> Note, that the Wiki page https://github.com/SCons/scons/wiki/WhySconsIsNotSlow (mentioned above, in the issue description) isn't reachable at the moment. There seems to be some more work required, in order to restore the old linkage and content of the WhySConsIsNotSlow topic...

I renamed the page to: https://github.com/SCons/scons/wiki/SCons-Performance

**Comment by bdbaddog** [comment]
Fixed

see updated page: https://github.com/SCons/scons/wiki/SCons-Performance
