### ISSUE TITLE
issue while installing scons

### ISSUE THREAD

**Issue by Gajuharale** [SCons/scons#3881]
**Describe the bug**

**Required information**
* Link to SCons Users thread discussing your issue.
* Version of SCons
* Version of Python
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
* How you installed SCons
* What Platform are you on? (Linux/Windows and which version)
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
* How you invoke scons (The command line you're using "scons --flags some_arguments")
desktop:~/SCons-4.1.0$ python3 setup.py install
running install
running bdist_egg
running egg_info
writing SCons.egg-info/PKG-INFO
writing dependency_links to SCons.egg-info/dependency_links.txt
writing entry points to SCons.egg-info/entry_points.txt
writing requirements to SCons.egg-info/requires.txt
writing top-level names to SCons.egg-info/top_level.txt
reading manifest file 'SCons.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.1' under directory 'build/doc/man'
writing manifest file 'SCons.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.linux-x86_64/egg
running install_data
error: can't copy 'build/doc/man/scons.1': doesn't exist or not a regular file

**Comment by Gajuharale** [comment]
Thank you for your response
I'm trying to install science tools using scons which can be providing
interface between fermitools

**Comment by mwichmann** [comment]
Right, I meant what form of SCons are you starting with - the scons tar/gz, or the scons-src tar/gz, or a git checkout? We normally suggest installing via pip like `python -m pip install scons` rather than installing via setuptools.  In a virtualenv if you want to keep the environment you work in private. I also was fishing for which version of SCons - since the bug I referenced acknowledged that one version of SCons did have those files missing in but that was expected to have been fixed.

**Comment by Gajuharale** [comment]
Thank you for the clarification.
I installed with conda
Thank you

**Comment by bdbaddog** [comment]
@Gajuharale  - If you noticed when initially filed this issue there are a set of questions we ask users to fill in to help us to help you.

Here's the important questions you didn't fill in when you initially filed this issue.
Please do so now.

1. Version of SCons
2. Version of Python
3. Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
- This you've answered "Conda"
4. How you installed SCons
- This you've answered "python3 setup.py install"
5. What Platform are you on? (Linux/Windows and which version)

Note as @mwichmann said above, This resembles and issue we fixed in the 4.1.0 release..
Pleas answer the remaining questions above.

**Comment by mwichmann** [comment]
Okay, a few comments, circling back on this.  If you installed via conda, it's possible they didn't pick up the minor update - the package on https://pypi.org is called SCons-4.1.0.post1 and has the fix for the `build/doc/man/scons.1` issue.  And if you got the tarball from sourceforge, it definitely doesn't have that fix.

**Comment by bdbaddog** [comment]
@Gajuharale - where did you download the SCons package you installed?

**Comment by bdbaddog** [comment]
Closing. No response. Please reopen if this is still an issue and provide requested information.
