### ISSUE TITLE
Install()'d files may not be writable (regression)

### ISSUE THREAD

**Issue by mwichmann** [SCons/scons#3927]
SCons 4.0.0 introduced a change to the code in the `Install` builder (and relatives) which stopped making the "installed" files writeable, unconditionally.  Although this behavior was not documented, dropping it is a regression from behavior users are depending on, namely the ability to do a subsequent build and not having it fail because existing files in the install location are read-only due to their source having been read-only, and now they can't be copied on top of.

The situation raises plenty of questions about "correct" behavior but those will be tracked elsewhere, this ticket is filed to restore the previous behavior, at least until some sensible alternative can be introduced.

scons-users mailing list link: http://four.pairlist.net/pipermail/scons-users/2021-April/008504.html

**Comment by merlin66** [comment]
Thanks for opening this issue.

Our use case is that we are distributing big binary data (resource files and dlls) to our build servers and developer machines with Perforce, which by default keeps files as read-only in its workspace. Our scons build copies files from there into the destination directory where our final built product ends up.

Whenever the source files change, SCons will copy the updated files to the destination directory.

We've relied on this use case working for a number of years, but it stopped working for us in SCons 4.0.0, since the Install builder now propagates the read-only property of the source file in this case. It now fails to overwrite a previously copied file unless we manually delete it first. Since a developer doesn't know which files to delete, he/she instead ends up clearing our entire target folder (including built targets) every time this happens.

One can certainly debate what is "correct". I would vote for a pragmatic solution, where SCons implements what is the most useful in typical build system use cases. Restoring the old behaviour until a better solution could be implemented would be great for us at least, and as far as I know it hasn't bothered a lot of user in the past.

I don't mind if proper thought is given to it though. It's good to get this kind of behaviour right.

**Comment by mwichmann** [comment]
Hmm, I just did a really simple test (with an eye to adding something to the testsuite for this), of course the first step is to make sure it fails on an unpatched scons, and if seems to install fine. What am I missing here?

**Comment by bdbaddog** [comment]
> Hmm, I just did a really simple test (with an eye to adding something to the testsuite for this), of course the first step is to make sure it fails on an unpatched scons, and if seems to install fine. What am I missing here?

Can you check the test into the PR and I'll take a look?

**Comment by mwichmann** [comment]
Run this twice - it doesn't fail the install the second time despite an existing read-only `bin/hello`

```python
import os
import pathlib

destdir = pathlib.Path("bin")
destdir.mkdir(exist_ok=True)

srcfile = pathlib.Path("hello")
if srcfile.exists():
    srcfile.chmod(0o644)
with srcfile.open(mode="w") as f:
    print("Hello from ", os.getpid(), file=f)
srcfile.chmod(0o444)

env = Environment(tools=["install"])
env.Install('bin', 'hello')
```

**Comment by merlin66** [comment]
I ran it twice here on Windows with scons-4.1.0.post1, and it fails here on the second run:
```$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: *** [bin\hello] K:\tmp\bin\hello: Access is denied
scons: building terminated because of errors.```

**Comment by mwichmann** [comment]
okay, so my mistake is doing this on my normal Linux system :) - thanks for that update, that means it *is* a usable beginning of a testcase.

**Comment by merlin66** [comment]
Interesting! Sorry I didn't specify operating system in my original report, I didn't think it was platform specific.

**Comment by mwichmann** [comment]
I didn't either.

Anyway, with the change/revert in PR #3931 the installed file is back to being writable, and thus repeated runs to install don't error out.
