### ISSUE TITLE
Obnoxious auto-package fetching... 

### ISSUE THREAD

**Issue by hergljkds** [SCons/scons#4408]
Auto-package-fetching in scons?  wtf.

How about a functional install script that works with setuptools in a sandbox?

**Comment by bdbaddog** [comment]
Closing. No WTF's appreciated. 
Feel free to bring your issues to the mailing list, IRC channel, or discord server.

**Comment by mwichmann** [comment]
It would really help if, when you follow @bdbaddog 's redirect, you describe the actual problem.  SCons doesn't even need to be "built", you can just run directly from source, or from the scons-local zipapp if you care to.  If you want to do a complete build, then there are some dependencies *for the documentation*, which uses the DocBook toolchain and Sphinx, and nothing is autofetched (the Python components of that are captured in `requirements-pkg.txt`).  Under the covers, the full build for building the uploadable wheel is in fact doing `python -m build` which is pretty functional and sandboxable.  At least, I always build in a virtualenv, but not a true sandbox due to the need for non-Python tools for the doc build, as mentioned.
